#!/bin/sh

if [ -z ${CONF} ]; then CONF=/etc/kvm-container.conf; fi

echo "using ${CONF} as configuration file"

check_load_config_file() {
if [ -f ${CONF} ]; then
    source ${CONF}
else
    echo "!! ${CONF} not found in path !!"
    exit 1
fi
}
