#!/bin/bash

# This is the uninstall script for kvm when run in a privileged
# container.

CONTAINER=kvm-server

# Check for read only root filesystem
is_read_only() {
   [[ -n $(awk '$2 ~ /\/host$/ && $4 ~ /(^|,)ro($|,)/' /host/proc/mounts) ]]
}

delete_file() {
PATH=$1
FILE=$2
if [ ! -z "${PATH}/${FILE}" ]; then
	if [ ! -e "${PATH}/${FILE}" ]; then
		echo "${FILE} not present, nothing to remove"
	else
		/usr/bin/rm -f ${PATH}/${FILE}
	fi
fi
}

BIN_INSTALL_PATH=$(is_read_only && echo "/host/usr/local/bin" || echo "/host/usr/bin")
SYSTEMD_INSTALL_PATH=$(is_read_only && echo "/host/usr/local/lib/systemd/system" || echo "/host/usr/lib/systemd/system")
QEMU_FIRM_PATH=$(is_read_only && echo "/host/usr/local/share/qemu" || echo "/host/usr/share/qemu")

# removing installed files
echo "LABEL UNINSTALL: Removing all files"
delete_file /host/etc ${CONTAINER}.conf 
delete_file /host/etc/libvirt/qemu/networks default_network.xml 
delete_file ${BIN_INSTALL_PATH} virt-install-demo.sh
delete_file ${BIN_INSTALL_PATH} ${CONTAINER}-manage

# Remove systemd unit files from host
for drv in qemu network nodedev nwfilter proxy secret storage; do
   delete_file ${SYSTEMD_INSTALL_PATH} container-virt${drv}d.service
   delete_file ${SYSTEMD_INSTALL_PATH} virt${drv}d.socket
   delete_file ${SYSTEMD_INSTALL_PATH} virt${drv}d-ro.socket
   delete_file ${SYSTEMD_INSTALL_PATH} virt${drv}d-admin.socket
done

for drv in log lock; do
   delete_file ${SYSTEMD_INSTALL_PATH} container-virt${drv}d.service
   delete_file ${SYSTEMD_INSTALL_PATH} virt${drv}d.socket
   delete_file ${SYSTEMD_INSTALL_PATH} virt${drv}d-admin.socket
done

delete_file ${SYSTEMD_INSTALL_PATH} virtproxyd-tls.socket
delete_file ${SYSTEMD_INSTALL_PATH} virtproxyd-tcp.socket
delete_file ${SYSTEMD_INSTALL_PATH} libvirtd.socket
delete_file ${SYSTEMD_INSTALL_PATH} libvirtd-ro.socket
delete_file ${SYSTEMD_INSTALL_PATH} libvirtd-admin.socket
delete_file ${SYSTEMD_INSTALL_PATH} libvirtd-tls.socket
delete_file ${SYSTEMD_INSTALL_PATH} libvirtd-tcp.socket
delete_file ${SYSTEMD_INSTALL_PATH} kvm-server-container.service

# Remove installed libvirt configs
/usr/bin/rm -rf /host/etc/libvirt
# Remove qemu data dir
/usr/bin/rm -rf ${QEMU_FIRM_PATH}
