#!/bin/bash

# This is the uninstall script for kvm when run in a privileged
# container.

CONTAINER=kvm-container
cd /
PATH="/usr/bin:/usr/sbin"

if [ ! -d /host/etc ] || [ ! -d /host/usr/local/bin ]; then
    echo "${CONTAINER}-uninstall: host file system is not mounted at /host"
    exit 1
fi

delete_file() {
PATH=$1
FILE=$2
if [ ! -z "${PATH}/${FILE}" ]; then
	if [ ! -e "${PATH}/${FILE}" ]; then
		echo "${FILE} not present, nothing to remove"
	else
		/usr/bin/rm -vf ${PATH}/${FILE}
	fi
fi
}

# removing installed files
echo "LABEL UNINSTALL: Removing all files"
delete_file /host/etc ${CONTAINER}.conf 
delete_file /host/etc ${CONTAINER}-functions
delete_file /host/etc/libvirt/qemu/networks sle_network.xml 
delete_file /host/usr/local/bin ${CONTAINER}-manage.sh
delete_file /host/usr/local/bin virsh
delete_file /host/usr/local/bin virt-install-demo.sh
delete_file /host/usr/local/bin virt-install
delete_file /host/usr/local/bin ${CONTAINER}-host-service

# Remove systemd unit files from host
for drv in qemu network nodedev nwfilter proxy secret storage; do
   delete_file /host/etc/systemd/system container-virt${drv}d.service
   delete_file /host/etc/systemd/system virt${drv}d.socket
   delete_file /host/etc/systemd/system virt${drv}d-ro.socket
   delete_file /host/etc/systemd/system virt${drv}d-admin.socket
done

for drv in log lock; do
   delete_file /host/etc/systemd/system container-virt${drv}d.service
   delete_file /host/etc/systemd/system virt${drv}d.socket
   delete_file /host/etc/systemd/system virt${drv}d-admin.socket
done

delete_file /host/etc/systemd/system virtproxyd-tls.socket
delete_file /host/etc/systemd/system virtproxyd-tcp.socket
delete_file /host/etc/systemd/system libvirtd.socket
delete_file /host/etc/systemd/system libvirtd-ro.socket
delete_file /host/etc/systemd/system libvirtd-admin.socket
delete_file /host/etc/systemd/system libvirtd-tls.socket
delete_file /host/etc/systemd/system libvirtd-tcp.socket
delete_file /host/etc/systemd/system kvm-container-meta.service
