#!/bin/bash
#set -exuo pipefail

# The XAUTHORITY from host must be readable
export XAUTHORITY="/tmp/.Xauthority"
if [ ! -f ${XAUTHORITY} ]; then
    echo "virt-manager in container: no ${XAUTHORITY} xauth file!"
    exit 1
fi

if [ -z "${DISPLAY:-}" ]; then
    echo "virt-manager in container: \$DISPLAY is not defined for graphical frontend"
    exit 1
fi

# TO DEBUG xterm is useful
#echo "xterm -e /usr/bin/virt-manager --debug --no-fork" > /tmp/l && chmod 755 /tmp/l
#echo DEBUG ${XAUTHORITY}
xterm -e /usr/bin/virt-manager --debug --no-fork
