#!/bin/bash

if [ -f /etc/kvm-container-functions ] ; then
    export CONF=/etc/kvm-container.conf
    . /etc/kvm-container-functions
elif [ -f `pwd`/kvm-container-functions ]; then
    echo "Found local version of kvm-container-functions"
    export CONF="`pwd`/kvm-container.conf"
    . "`pwd`/kvm-container-functions"
else
    echo "! need /etc/kvm-container-functions; Exiting";
    exit 1
fi
check_load_config_file

set -euxo pipefail

# Run the domain
podman exec -ti ${CONTAINER_NAME} virt-scenario-launch $@
